spring:
  datasource:
    url: jdbc:mysql://localhost/diklatdb
    username: root
    password: null
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent-output: true
security:
  user:
    password: none